<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SerialDebugAssistant</AssemblyName>
    <RootNamespace>SerialDebugAssistant</RootNamespace>
    <Version>0.9.3</Version>
    <Product>Comm Terminal</Product>
    <Title>Comm Terminal</Title>
    <Company>Comm Terminal</Company>
    <StartupObject>SerialDebugAssistant.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

</Project>
